DROP TABLE IF EXISTS ryzlan.arr_commerce_connect_edit;
CREATE TABLE ryzlan.arr_commerce_connect_edit AS WITH base AS (
  SELECT *
  FROM ufdm_archive.arr_lcoked_09072024_2201
  WHERE temp_product_group_li IN (
      'Commerce Connect',
      'Commerce Connect M&S',
      'Commerce Connect Subscription'
    )
),
base_rest AS (
  SELECT *
  FROM ufdm_archive.arr_lcoked_09072024_2201
  WHERE temp_product_group_li NOT IN (
      'Commerce Connect',
      'Commerce Connect M&S',
      'Commerce Connect Subscription'
    )
),
base_cc AS (
  SELECT *
  FROM base
  WHERE temp_product_group_li = 'Commerce Connect'
),
base_cc_ms AS (
  SELECT *
  FROM base
  WHERE temp_product_group_li = 'Commerce Connect M&S'
),
base_cc_subs AS (
  SELECT *
  FROM base
  WHERE temp_product_group_li = 'Commerce Connect Subscription'
),
split_base_cc AS (
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.3 AS baseline_mrr_local_currency,
    baseline_arr_local_currency * 0.3 AS baseline_arr_local_currency,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.3 AS mrr_usd_ccfx,
    arr_usd_ccfx * 0.3 AS arr_usd_ccfx,
    fx_rate_mefx,
    mrr_usd_mefx * 0.3 AS mrr_usd_mefx,
    arr_usd_mefx * 0.3 AS arr_usd_mefx,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.3 AS mrr_usd_actualfx,
    arr_usd_actualfx * 0.3 AS arr_usd_actualfx,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    sku,
    sku_name,
    product_name,
    product_group,
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    new_product_solution,
    new_product_line,
    updated_product_group,
    new_product,
    new_line_of_business,
    new_line_of_business_sub_category,
    modified_comments,
    temp_product_solution_li,
    temp_product_group_li,
    temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.30 as baseline_arr_local_currency_original,
    migration_from,
    migration_to
  FROM base_cc
  UNION ALL
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.7,
    baseline_arr_local_currency * 0.7,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.7,
    arr_usd_ccfx * 0.7,
    fx_rate_mefx,
    mrr_usd_mefx * 0.7,
    arr_usd_mefx * 0.7,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.7,
    arr_usd_actualfx * 0.7,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    b.product_code,
    -- sku,
    b.product_name,
    -- sku_name,
    b.product,
    --product_name,
    b.product_group,
    --product_group 
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    b.product_solution,
    -- new_product_solution,
    b.product_line,
    -- new_product_line,
    b.product_group,
    -- updated_product_group,
    b.product,
    -- new_product,
    b.new_line_of_business,
    -- new_line_of_business,
    b.new_line_of_business_subcategory,
    -- new_line_of_business_sub_category,
    modified_comments,
    b.temp_product_solution_li,
    b.temp_product_group_li,
    b.temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.70 as baseline_arr_local_currency_original,
    b."Mig From Name" as migration_from,
    b."Mig to Name" as migration_to
  FROM base_cc AS a
    JOIN ryzlan.tmjs_com_mod AS b ON b.product_code = 'ALLOCA-CMPPASS'
),
split_base_ms AS (
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.3 AS baseline_mrr_local_currency,
    baseline_arr_local_currency * 0.3 AS baseline_arr_local_currency,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.3 AS mrr_usd_ccfx,
    arr_usd_ccfx * 0.3 AS arr_usd_ccfx,
    fx_rate_mefx,
    mrr_usd_mefx * 0.3 AS mrr_usd_mefx,
    arr_usd_mefx * 0.3 AS arr_usd_mefx,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.3 AS mrr_usd_actualfx,
    arr_usd_actualfx * 0.3 AS arr_usd_actualfx,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    sku,
    sku_name,
    product_name,
    product_group,
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    new_product_solution,
    new_product_line,
    updated_product_group,
    new_product,
    new_line_of_business,
    new_line_of_business_sub_category,
    modified_comments,
    temp_product_solution_li,
    temp_product_group_li,
    temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.30 as baseline_arr_local_currency_original,
    migration_from,
    migration_to
  FROM base_cc_ms
  UNION ALL
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.7,
    baseline_arr_local_currency * 0.7,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.7,
    arr_usd_ccfx * 0.7,
    fx_rate_mefx,
    mrr_usd_mefx * 0.7,
    arr_usd_mefx * 0.7,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.7,
    arr_usd_actualfx * 0.7,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    b.product_code,
    -- sku,
    b.product_name,
    -- sku_name,
    b.product,
    --product_name,
    b.product_group,
    --product_group 
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    b.product_solution,
    -- new_product_solution,
    b.product_line,
    -- new_product_line,
    b.product_group,
    -- updated_product_group,
    b.product,
    -- new_product,
    b.new_line_of_business,
    -- new_line_of_business,
    b.new_line_of_business_subcategory,
    -- new_line_of_business_sub_category,
    modified_comments,
    b.temp_product_solution_li,
    b.temp_product_group_li,
    b.temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.70 as baseline_arr_local_currency_original,
    b."Mig From Name" as migration_from,
    b."Mig to Name" as migration_to
  FROM base_cc_ms AS a
    JOIN ryzlan.tmjs_com_mod AS b ON b.product_code = 'ALLOCA-CMPPASSM&S'
),
split_base_subs AS (
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.3 AS baseline_mrr_local_currency,
    baseline_arr_local_currency * 0.3 AS baseline_arr_local_currency,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.3 AS mrr_usd_ccfx,
    arr_usd_ccfx * 0.3 AS arr_usd_ccfx,
    fx_rate_mefx,
    mrr_usd_mefx * 0.3 AS mrr_usd_mefx,
    arr_usd_mefx * 0.3 AS arr_usd_mefx,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.3 AS mrr_usd_actualfx,
    arr_usd_actualfx * 0.3 AS arr_usd_actualfx,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    sku,
    sku_name,
    product_name,
    product_group,
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    new_product_solution,
    new_product_line,
    updated_product_group,
    new_product,
    new_line_of_business,
    new_line_of_business_sub_category,
    modified_comments,
    temp_product_solution_li,
    temp_product_group_li,
    temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.30 as baseline_arr_local_currency_original,
    migration_from,
    migration_to
  FROM base_cc_subs
  UNION ALL
  SELECT id,
    snapshot_date,
    c_name,
    parent_customer_ns_id,
    end_customer_ns_id,
    parent_customer,
    end_customer,
    parent_master_customer_id,
    end_customer_master_customer_id,
    parent_salesforce_id,
    end_customer_salesforce_id,
    line_type,
    baseline_currency,
    subsidiary_base_currency,
    recurring_amount,
    baseline_mrr_local_currency * 0.7,
    baseline_arr_local_currency * 0.7,
    ccfx_date,
    mefx_date,
    fx_rate_ccfx,
    mrr_usd_ccfx * 0.7,
    arr_usd_ccfx * 0.7,
    fx_rate_mefx,
    mrr_usd_mefx * 0.7,
    arr_usd_mefx * 0.7,
    fx_rate_actualfx,
    mrr_usd_actualfx * 0.7,
    arr_usd_actualfx * 0.7,
    bill_freq,
    term_months,
    date_start,
    date_end,
    date_termination,
    subline_id,
    reference_number,
    line_number,
    revision_number,
    change_order,
    status,
    catalog_type,
    b.product_code,
    -- sku,
    b.product_name,
    -- sku_name,
    b.product,
    --product_name,
    b.product_group,
    --product_group 
    product_family,
    arr_source,
    sco_action_id,
    sco_memo,
    sco_modification_type,
    subsidiary_entity_name,
    legacy_org,
    mcid,
    created_date,
    modified_date,
    snapshot_date_revised,
    b.product_solution,
    -- new_product_solution,
    b.product_line,
    -- new_product_line,
    b.product_group,
    -- updated_product_group,
    b.product,
    -- new_product,
    b.new_line_of_business,
    -- new_line_of_business,
    b.new_line_of_business_subcategory,
    -- new_line_of_business_sub_category,
    modified_comments,
    b.temp_product_solution_li,
    b.temp_product_group_li,
    b.temp_product_line_li,
    baseline_currency_original,
    fx_rate_ccfx_original,
    cast(baseline_arr_local_currency_original as numeric) * 0.70 as baseline_arr_local_currency_original,
    b."Mig From Name" as migration_from,
    b."Mig to Name" as migration_to
  FROM base_cc_subs AS a
    JOIN ryzlan.tmjs_com_mod AS b ON b.product_code = 'ALLOCA-CMPPASSSUB'
),
combined_splits as (
  SELECT *
  FROM split_base_cc
  UNION ALL
  SELECT *
  FROM split_base_ms
  UNION ALL
  SELECT *
  FROM split_base_subs
)
SELECT id,
  snapshot_date,
  c_name,
  parent_customer_ns_id,
  end_customer_ns_id,
  parent_customer,
  end_customer,
  parent_master_customer_id,
  end_customer_master_customer_id,
  parent_salesforce_id,
  end_customer_salesforce_id,
  line_type,
  baseline_currency,
  subsidiary_base_currency,
  recurring_amount,
  baseline_mrr_local_currency,
  baseline_arr_local_currency,
  ccfx_date,
  mefx_date,
  fx_rate_ccfx,
  mrr_usd_ccfx,
  arr_usd_ccfx,
  fx_rate_mefx,
  mrr_usd_mefx,
  arr_usd_mefx,
  fx_rate_actualfx,
  mrr_usd_actualfx,
  arr_usd_actualfx,
  bill_freq,
  term_months,
  date_start,
  date_end,
  date_termination,
  subline_id,
  reference_number,
  line_number,
  revision_number,
  change_order,
  status,
  catalog_type,
  sku,
  sku_name,
  product_name,
  product_group,
  product_family,
  arr_source,
  sco_action_id,
  sco_memo,
  sco_modification_type,
  subsidiary_entity_name,
  legacy_org,
  mcid,
  created_date,
  modified_date,
  snapshot_date_revised,
  new_product_solution,
  new_product_line,
  updated_product_group,
  new_product,
  new_line_of_business,
  new_line_of_business_sub_category,
  modified_comments,
  temp_product_solution_li,
  temp_product_group_li,
  temp_product_line_li,
  baseline_currency_original,
  fx_rate_ccfx_original,
  baseline_arr_local_currency_original,
  migration_to,
  migration_from
FROM base_rest
UNION ALL
select id,
  snapshot_date,
  c_name,
  parent_customer_ns_id,
  end_customer_ns_id,
  parent_customer,
  end_customer,
  parent_master_customer_id,
  end_customer_master_customer_id,
  parent_salesforce_id,
  end_customer_salesforce_id,
  line_type,
  baseline_currency,
  subsidiary_base_currency,
  recurring_amount,
  baseline_mrr_local_currency,
  baseline_arr_local_currency,
  ccfx_date,
  mefx_date,
  fx_rate_ccfx,
  mrr_usd_ccfx,
  arr_usd_ccfx,
  fx_rate_mefx,
  mrr_usd_mefx,
  arr_usd_mefx,
  fx_rate_actualfx,
  mrr_usd_actualfx,
  arr_usd_actualfx,
  bill_freq,
  term_months,
  date_start,
  date_end,
  date_termination,
  subline_id,
  reference_number,
  line_number,
  revision_number,
  change_order,
  status,
  catalog_type,
  sku,
  sku_name,
  product_name,
  product_group,
  product_family,
  arr_source,
  sco_action_id,
  sco_memo,
  sco_modification_type,
  subsidiary_entity_name,
  legacy_org,
  mcid,
  created_date,
  modified_date,
  snapshot_date_revised,
  new_product_solution,
  new_product_line,
  updated_product_group,
  new_product,
  new_line_of_business,
  new_line_of_business_sub_category,
  modified_comments,
  temp_product_solution_li,
  temp_product_group_li,
  temp_product_line_li,
  baseline_currency_original,
  fx_rate_ccfx_original,
  cast(baseline_arr_local_currency_original as text) as baseline_arr_local_currency_original,
  migration_to,
  migration_from
from combined_splits;