create or replace task VAULT_FIVETRAN.OPTI_SALESFORCE.TASK_QUALIFIED_LEAD_C_SNAPSHOT schedule = 'USING CRON 0 22 * * * America/Los_Angeles' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL' as
Insert into "VAULT_FIVETRAN"."OPTI_SALESFORCE"."QUALIFIED_LEAD_C_SNAPSHOT" (
    id,
    contact_c,
    lead_c,
    name,
    opportunity_c,
    DATE_STATUS_NEW_C,
    DATE_STATUS_ENGAGED_C,
    DATE_STATUS_QUALIFIED_C,
    DATE_STATUS_SPL_C,
    DATE_STATUS_SAL_C,
    DATE_STATUS_OPPORTUNITY_C,
    DATE_STATUS_RECYCLED_C,
    DATE_STATUS_DISQUALIFIED_C,
    DATE_STATUS_CUSTOMER_C,
    DATE_STATUS_SQL_C,
    SNAPSHOT_LOAD_DATE
  )
select id,
  contact_c,
  lead_c,
  name,
  opportunity_c,
  DATE_STATUS_NEW_C,
  DATE_STATUS_ENGAGED_C,
  DATE_STATUS_QUALIFIED_C,
  DATE_STATUS_SPL_C,
  DATE_STATUS_SAL_C,
  DATE_STATUS_OPPORTUNITY_C,
  DATE_STATUS_RECYCLED_C,
  DATE_STATUS_DISQUALIFIED_C,
  DATE_STATUS_CUSTOMER_C,
  DATE_STATUS_SQL_C,
  current_timestamp()
from "VAULT_FIVETRAN"."OPTI_SALESFORCE"."QUALIFIED_LEAD_C"
where created_date > '2021-09-30 23:59:59.000 +0000';