create or replace task VAULT_FIVETRAN.OPTI_SALESFORCE.TASK_FORECASTS_SNAPSHOT schedule = 'USING CRON 30 16 * * MON America/Los_Angeles' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL' as
insert into "VAULT_FIVETRAN"."POSTGRES_CLARI"."FORECASTS_SNAPSHOT"
select *,
  current_timestamp() as SNAPSHOT_LOAD_DATE
from "VAULT_FIVETRAN"."POSTGRES_CLARI"."FORECASTS"
where TIME_PERIOD_ID in (
    select YEAR(CURRENT_TIMESTAMP()) || '_Q' || QUARTER(CURRENT_TIMESTAMP())
  );