- Line of Business (LOB) = ‘ Licenses ’ > Line of Business (LOB) = ‘ Cloud ’ 
- Product = ‘ Ektron ’ > Product = ‘ Content Management System (CMS) ’ 
- Product = ‘ Everweb ’ > Product = ‘ Content Management System (CMS) ’ 
- Product = ’ Find ’ > Product = ‘ Content Graph ’ 
- Product = ’ Visitor Intelligence ’ > Product = ‘ Data Platform (ODP) ’